
GET http://localhost:2411/
Cookie: acccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OGZhNzU3YTM0ZTI2ZmEwMzZjMjY5MyIsImlhdCI6MTcwMzkxNjc4NSwiZXhwIjoxNzAzOTIwMzg1fQ.nMvu_AoOpHNURhpQjaZSPShXGe_ppDXjCcC3xwvV5lM