### check server


POST http://localhost:2411/api/auth/register
Content-Type: application/json

{
    "displayName": "David Beckham",
    "email": "beckham123@gmail.com",
    "password": "123123"
}

###


POST http://localhost:2411/api/auth/login
Content-Type: application/json

{
    "email": "ronaldo123@gmail.com",
    "password": "123123"
}

###

POST http://localhost:2411/api/auth/forgot-password
Content-Type: application/json

{
    "email": "lequanphat3579@gmail.com"
}

###
POST http://localhost:2411/api/auth/forgot-password
Content-Type: application/json

{
    "email": "lequanphat3579@gmail.com"
}

###
POST http://localhost:2411/api/auth/change-password
Content-Type: application/json

{
    "password": "abc123",
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1N2NhOWZjNDJlNDRmMzdjNWU1ZTBlOCIsImlhdCI6MTcwMjc0MzMxOSwiZXhwIjoxNzAyNzQzNjE5fQ.z7TsSQDAR53TgM4DD8cfLGa52xQlvjjXAbXRDbcmk9c"
}

###

POST http://localhost:2411/api/auth/logout
Content-Type: application/json
# Set-Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmI2ZTViNjg0ODViZDdhOWI2MTYwYyIsImlhdCI6MTcwMTc2NjEzMCwiZXhwIjoxNzAxNzY3OTMwfQ.2suBhtT392ZsJZ26VOugS7aAZE635gl4xh72Fbh-otw



###

GET http://localhost:2411/api/user/all-users/657eaa2600c3a388fb6c5b91
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1N2VhYTI2MDBjM2EzODhmYjZjNWI5MSIsImlhdCI6MTcwMjgyMzk1MywiZXhwIjoxNzAyODI0MjUzfQ.hUq8xGAUwt0PWzL9TZnuLixYqE9UR-JPwLj-dyaHJrk

###

GET http://localhost:2411/api/auth/refresh-token