### check server


POST http://localhost:2411/api/auth/register
Content-Type: application/json

{
    "email": "lequanphat3579@gmail.com",
    "password": "abc12345"
}

###


POST http://localhost:2411/api/auth/login
Content-Type: application/json

{
    "email": "lequanphat3579@gmail.com",
    "password": "abc12345"
}

### 

POST http://localhost:2411/api/auth/logout
Content-Type: application/json
# Set-Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmI2ZTViNjg0ODViZDdhOWI2MTYwYyIsImlhdCI6MTcwMTc2NjEzMCwiZXhwIjoxNzAxNzY3OTMwfQ.2suBhtT392ZsJZ26VOugS7aAZE635gl4xh72Fbh-otw

{
    "username": "quanphat"
}

###

GET http://localhost:2411/api/user/all-users/656b6e5b68485bd7a9b6160c
Content-Type: application/json

{
    "username": "quanphat"
}

###

GET http://localhost:2411/api/auth/refresh-token